"""add products catalog and product_id links

Revision ID: 03d6037c3134
Revises: b34b28dd4a32
Create Date: 2026-08-30 01:23:09.306483

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '03d6037c3134'
down_revision = 'b34b28dd4a32'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('products',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('canonical_name', sa.Text(), nullable=False),
    sa.Column('category', sa.String(length=255), nullable=True),
    sa.Column('unit_of_measure', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('order_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('product_id', sa.Uuid(), nullable=True))
        batch_op.create_foreign_key(None, 'products', ['product_id'], ['id'])

    with op.batch_alter_table('product_labels', schema=None) as batch_op:
        batch_op.add_column(sa.Column('product_id', sa.Uuid(), nullable=True))
        batch_op.create_foreign_key(None, 'products', ['product_id'], ['id'])
    # ### end Alembic commands ###
    # NOTE: autogenerate also proposed dropping 'scans_search_idx' here (same
    # spurious diff as every prior migration — it isn't in the ORM metadata).


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product_labels', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('product_id')

    with op.batch_alter_table('order_items', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('product_id')

    op.drop_table('products')
    # ### end Alembic commands ###
