"""add supplier orders, order items, product labels

Revision ID: 6aa4e079d457
Revises: 9148018fb2c1
Create Date: 2026-08-26 14:06:13.735319

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '6aa4e079d457'
down_revision = '9148018fb2c1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('supplier_orders',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('supplier_name', sa.String(length=255), nullable=True),
    sa.Column('order_number', sa.String(length=100), nullable=True),
    sa.Column('order_date', sa.Date(), nullable=True),
    sa.Column('blob_name', sa.String(length=512), nullable=False),
    sa.Column('blob_url', sa.String(length=1024), nullable=False),
    sa.Column('raw_result', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('order_items',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('order_id', sa.Uuid(), nullable=False),
    sa.Column('product_name', sa.Text(), nullable=False),
    sa.Column('product_code', sa.String(length=100), nullable=True),
    sa.Column('quantity', sa.Numeric(precision=12, scale=3), nullable=True),
    sa.Column('unit_price', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('raw_line', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['supplier_orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('product_labels',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('order_id', sa.Uuid(), nullable=True),
    sa.Column('matched_order_item_id', sa.Uuid(), nullable=True),
    sa.Column('blob_name', sa.String(length=512), nullable=False),
    sa.Column('blob_url', sa.String(length=1024), nullable=False),
    sa.Column('raw_result', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('product_name', sa.Text(), nullable=True),
    sa.Column('expiration_date', sa.Date(), nullable=True),
    sa.Column('lot_number', sa.String(length=100), nullable=True),
    sa.Column('match_status', sa.String(length=30), nullable=False),
    sa.Column('match_score', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['matched_order_item_id'], ['order_items.id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['supplier_orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
    # NOTE: autogenerate also proposed dropping 'scans_search_idx' here, since
    # that expression index isn't represented in the ORM metadata (it was
    # added by hand in the initial migration). That's spurious — removed.


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('product_labels')
    op.drop_table('order_items')
    op.drop_table('supplier_orders')
    # ### end Alembic commands ###
