"""create scans table

Revision ID: 9148018fb2c1
Revises: 
Create Date: 2026-08-25 20:49:02.126652

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '9148018fb2c1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scans',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('source_filename', sa.String(length=255), nullable=False),
    sa.Column('content_type', sa.String(length=100), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('blob_name', sa.String(length=512), nullable=False),
    sa.Column('blob_url', sa.String(length=1024), nullable=False),
    sa.Column('caption', sa.Text(), nullable=True),
    sa.Column('caption_confidence', sa.Float(), nullable=True),
    sa.Column('tags', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('ocr_text', sa.Text(), nullable=True),
    sa.Column('raw_result', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###

    # Hand-written: Alembic autogenerate doesn't detect expression indexes.
    # Must stay identical to models.SEARCH_VECTOR_SQL, or Postgres won't use
    # this index for queries built from that constant.
    op.execute(
        "CREATE INDEX scans_search_idx ON scans "
        "USING gin (to_tsvector('english', coalesce(caption, '') || ' ' || coalesce(ocr_text, '')))"
    )


def downgrade():
    op.execute("DROP INDEX IF EXISTS scans_search_idx")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('scans')
    # ### end Alembic commands ###
