"""add product_forecasts table

Revision ID: 9905fe0eb107
Revises: 03d6037c3134
Create Date: 2026-08-30 01:36:43.900130

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9905fe0eb107'
down_revision = '03d6037c3134'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product_forecasts',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('product_id', sa.Uuid(), nullable=False),
    sa.Column('predicted_quantity', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.Column('method', sa.String(length=50), nullable=False),
    sa.Column('predicted_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
    # NOTE: autogenerate also proposed dropping 'scans_search_idx' here (same
    # spurious diff as every prior migration — it isn't in the ORM metadata).


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('product_forecasts')
    # ### end Alembic commands ###
