"""add scan_reviews table

Revision ID: b34b28dd4a32
Revises: 6aa4e079d457
Create Date: 2026-08-30 00:41:25.424713

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'b34b28dd4a32'
down_revision = '6aa4e079d457'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scan_reviews',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('scan_id', sa.Uuid(), nullable=False),
    sa.Column('lines', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['scan_id'], ['scans.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('scan_id')
    )
    # ### end Alembic commands ###
    # NOTE: autogenerate also proposed dropping 'scans_search_idx' here (same
    # spurious diff as the previous migration — it isn't in the ORM metadata).


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('scan_reviews')
    # ### end Alembic commands ###
